name: portfilio
description: Thành Portfilio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.3
  scrollable_positioned_list: ^0.3.8

  bloc: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - images/

