name: portfilio
description: Thành Portfilio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.5
  animated_text_kit: ^4.2.2
  scrollable_positioned_list: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - images/

