name: portfilio
description: Thành Portfilio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.20
  animated_text_kit: ^4.2.1
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  assets:
    - images/

